name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  DOTNETVERSION: "8.0.x"
  APP: "QuickAnki"
  SOLUTION: "./QuickAnki.sln"
  BUILDOUTPUTPATH_LINUX: "/home/runner/work/QuickAnki/QuickAnki/QuickAnki/bin/Release/net8.0/linux-x64/publish"
  BUILDOUTPUTPATH_WIN: "/home/runner/work/QuickAnki/QuickAnki/QuickAnki/bin/Release/net8.0/win-x64/publish"
#  PACKOUTPUTPATH: "./out"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Setup .NET Core SDK ${{ env.DOTNETVERSION }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ env.DOTNETVERSION }}

      - name: Get version
        id: version
        uses: battila7/get-version-action@v2

      - name: Get previous release tag
        id: previousTag
        uses: sammcoe/get-previous-release-action@v1.0.3

      - name: Install dependencies
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Build Linux
        run: dotnet publish ${{ env.SOLUTION }} -r linux-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None -p:DebugSymbols=false --self-contained

      - name: Build Windows
        run: dotnet publish ${{ env.SOLUTION }} -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None -p:DebugSymbols=false --self-contained  

      - name: Upload app build artifact Linux
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP }}-${{ steps.version.outputs.version-without-v }}
          path: ${{ env.BUILDOUTPUTPATH_LINUX }}
          
      - name: Upload app build artifact Windows
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP }}-${{ steps.version.outputs.version-without-v }}
          path: ${{ env.BUILDOUTPUTPATH_WIN }}    
          
      - name: GitHub release
        uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ steps.version.outputs.version-without-v }}
          tag_name: ${{ github.ref }}
          body: ${{ env.LOG }}
          draft: false
          prerelease: false

      - name: ZIP release artifact Linux
        run: echo $(pwd); echo $(find . -type d); cd ${{ env.BUILDOUTPUTPATH_LINUX }}; zip -r ../${{ env.APP }}-${{ steps.version.outputs.version-without-v }}-linux64.zip ./

      - name: ZIP release artifact Windows
        run: echo $(pwd); echo $(find . -type d); cd ${{ env.BUILDOUTPUTPATH_WIN }}; zip -r ../${{ env.APP }}-${{ steps.version.outputs.version-without-v }}-win64.zip ./

      - name: GitHub release assets Linux
        uses: actions/upload-release-asset@v1
        id: release_assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ env.BUILDOUTPUTPATH_LINUX }}/../${{ env.APP }}-${{ steps.version.outputs.version-without-v }}-linux64.zip
          asset_name: ${{ env.APP }}-${{ steps.version.outputs.version-without-v }}.zip
          asset_content_type: application/zip
      
      - name: GitHub release assets Windows
        uses: actions/upload-release-asset@v1
        id: release_assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ env.BUILDOUTPUTPATH_LINUX }}/../${{ env.APP }}-${{ steps.version.outputs.version-without-v }}-win64.zip
          asset_name: ${{ env.APP }}-${{ steps.version.outputs.version-without-v }}.zip
          asset_content_type: application/zip
